import React from "react";
import Header from "../header/header";
import Footer from "../footer/footer";
import "./aboutus.css";

export default function AboutUs() {
  return (
    <div>
      <Header />
      <div class="aboutus">
        <div class="about-section">
          <div class="inner-container">
            <h1>Candle In The Wind - About Us</h1>
            <p class="text">
              CandleInTheWind Store wants to develop an application to promote
              and increase sales for the store. The main types of products sold
              are candles, essential oils, scented waxes, decorative products,
              and accessories. In addition, the shop is also a club of essential
              oil lovers, sharing activities and allowing customers to exchange
              essential oils and candles . With that in mind, the specific
              functions of the system are as follows:
            </p>
            <p class="text">
              - The store can manage products, product categories, order
              management and loyalty.
            </p>
            <p class="text">
              - Customers can register to become loyal customers and enjoy
              promotions by promotional codes from the store. Customers can buy
              goods at the store or order on the web, the form of payment is
              cash upon receipt and the shipping fee will be ordered by the
              customer from the shipping unit and the customer will pay with the
              money. . The system therefore only manages orders and order
              status, not shipping or delivery.{" "}
            </p>
            <p class="text">
              - Customers who have different tiers and earn points according to
              their orders can also use the points to redeem products in the
              store according to the redemption codes generated by the store.
            </p>
            <p class="text">
              - Stores can generate promotional codes for loyal customers to
              apply when shopping online and in-store. Promo code will have a
              certain period of use and number of uses.
            </p>
            <p class="text">
              - Candle exchange between members allows management of posts by
              members, posts must be approved by the store before being posted,
              each post allows other members to comment.
            </p>
            <div class="skills">
              <span>Candle</span>
              <span>Scented wax & Illustrator</span>
              <span>Decorations</span>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
